version: 2.1

jobs:
 common_build:
  docker:
    - image: circleci/openjdk:11

  steps:
    - checkout
    - run:
       name: Build Java App
        command: |
          # build command
          ./gradlew clean build